### ISSUE TITLE
Return error when doesn't have a password.

### ISSUE THREAD

**Issue by cauealves** [kevva/wifi-password#11]
When I'm connected on a public wifi and execute the `wifi-password`, returns:
```bash
Error: Your network doesn't have a password
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
I believe this is not a `error` and it should return to the screen. This is normal behavior. 

What do you think about this? Maybe we can predict the behavior inside the code and sending a report with a better way..

**Comment by SamVerschueren** [comment]
It should just print the message without the stacktrace :+1:
