### ISSUE TITLE
Error on Windows 10

### ISSUE THREAD

**Issue by roccomuso** [kevva/wifi-password#15]
I'm having this error on Windows 10, with node v6.6.0:

```
Error: Promise rejected with value: 'Could not get password'
    at C:\Users\Antonio\AppData\Roaming\npm\node_modules\wifi-password-cli\node_modules\loud-rejection\index.js:27:12
    at Array.forEach (native)
    at EventEmitter.<anonymous> (C:\Users\Antonio\AppData\Roaming\npm\node_modules\wifi-password-cli\node_modules\loud-rejection\index.js:23:24)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at emit (C:\Users\Antonio\AppData\Roaming\npm\node_modules\wifi-password-cli\node_modules\signal-exit\index.js:68:11)
    at processEmit [as emit] (C:\Users\Antonio\AppData\Roaming\npm\node_modules\wifi-password-cli\node_modules\signal-exit\index.js:141:5)
```

**Comment by GreenLantern101** [comment]
basically the script just executes `wlan show profile name=[SSID] key=clear` on Win10

**Comment by tyeth** [comment]
Prepend that command with

 netsh
